FROM python:3.11-bullseye

# Dependencias del sistema
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    unzip \
    gnupg \
    ca-certificates \
    fonts-liberation \
    fonts-dejavu \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    xdg-utils \
    libgbm1 \
    libgtk-3-0 \
    libu2f-udev \
    libvulkan1 \
    git \
    xvfb \
    x11vnc \
    supervisor \
    net-tools \
    python3-tk \
    scrot \
    libxss1 \
    libxtst6 \
    xdotool \
    wmctrl \
    dbus-x11 \
    gnome-screenshot \
    openbox \
    x11-utils \
    libx11-6 \
    libxext6 \
    libxrender1 \
    xauth \
    pandoc \
    libcairo2 \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libgdk-pixbuf-2.0-0 \
    libffi-dev \
    shared-mime-info \
    && rm -rf /var/lib/apt/lists/*

# Chrome
ENV CHROME_VERSION=145.0.7632.109

RUN wget -O /tmp/chrome.zip \
    https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-linux64.zip \
    && unzip /tmp/chrome.zip -d /opt/ \
    && ln -s /opt/chrome-linux64/chrome /usr/bin/google-chrome \
    && rm /tmp/chrome.zip

# ChromeDriver
RUN wget -O /tmp/chromedriver.zip \
    https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip \
    && unzip /tmp/chromedriver.zip -d /opt/ \
    && mv /opt/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver \
    && chmod +x /usr/local/bin/chromedriver \
    && rm /tmp/chromedriver.zip

# noVNC
RUN git clone --depth 1 https://github.com/novnc/noVNC.git /opt/novnc \
    && git clone --depth 1 https://github.com/novnc/websockify /opt/websockify \
    && ln -s /opt/novnc/vnc.html /opt/novnc/index.html

# librerías Python comunes
RUN pip install --no-cache-dir \
    selenium \
    requests \
    pandas \
    openpyxl \
    pdfplumber \
    weasyprint
